import Footer from '@/layout/footer';
import Header from '@/layout/header';
import type { Metadata } from 'next';

import { satoshi } from './font';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${satoshi.className} text-body`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
