import Provider from '@/components/provider';
import Footer from '@/layout/footer';
import Header from '@/layout/header';
import type { Metadata } from 'next';

import { bricolage, satoshi } from './font';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='no-visible-scrollbar' lang='en'>
      <body
        className={`${satoshi.className} ${bricolage.variable} text-body`}
      >
        <Provider>
          <Header />
          {children}
        </Provider>

        <Footer />
      </body>
    </html>
  );
}
